### ISSUE TITLE
1.17 error

### ISSUE THREAD

**Issue by NamiUni** [InsightsPlugin/Insights#105]
## error
```
[01:06:17 ERROR]: Could not pass event BlockMultiPlaceEvent to Insights v6.4.0
java.lang.ExceptionInInitializerError: null
        at dev.frankheijden.insights.listeners.BlockListener.onBlockPlace(BlockListener.java:62) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callBlockMultiPlaceEvent(CraftEventFactory.java:360) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.world.item.ItemStack.placeItem(ItemStack.java:372) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:568) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1743) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1340) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1319) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1312) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1273) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1184) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: dev.frankheijden.insights.dependencies.minecraftreflection.exceptions.MinecraftReflectionException: Invalid class 'net.minecraft.server.v1_17_R1.BlockPosition'!
        at dev.frankheijden.insights.dependencies.minecraftreflection.Reflection.getClassFromName(Reflection.java:40) ~[?:?]
        at dev.frankheijden.insights.dependencies.minecraftreflection.MinecraftReflection.of(MinecraftReflection.java:20) ~[?:?]
        at dev.frankheijden.insights.api.utils.BlockUtils.<clinit>(BlockUtils.java:20) ~[?:?]
        ... 26 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.BlockPosition
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at dev.frankheijden.insights.dependencies.minecraftreflection.Reflection.getClassFromName(Reflection.java:38) ~[?:?]
        at dev.frankheijden.insights.dependencies.minecraftreflection.MinecraftReflection.of(MinecraftReflection.java:20) ~[?:?]
        at dev.frankheijden.insights.api.utils.BlockUtils.<clinit>(BlockUtils.java:20) ~[?:?]
        ... 26 more
[01:06:20 ERROR]: Could not pass event BlockBreakEvent to Insights v6.4.0
java.lang.NoClassDefFoundError: Could not initialize class dev.frankheijden.insights.api.utils.BlockUtils
        at dev.frankheijden.insights.listeners.BlockListener.onBlockBreak(BlockListener.java:112) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor25.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:369) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:329) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:219) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1677) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1340) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1319) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1312) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1273) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1184) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"33a04d9"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

## Actions to reproduce (if known)
Put Insight in the plugins folder and start it. place and destroy the bed.

## pluginlist
insights-6.4.0

## server version
paper-1.17-28.jar

**Comment by FrankHeijden** [comment]
Thanks for reporting! It's been fixed in v6.4.1 :)

**Comment by NamiUni** [comment]
Thank you for your quick response. It's my favorite plugin and I'm supporting it. Have a great day.
