### ISSUE TITLE
1.19.3 - Plugin Startup Error

### ISSUE THREAD

**Issue by mayberks** [InsightsPlugin/Insights#190]
`
[00:49:18 INFO]: [Insights] Enabling Insights v6.13.0
[00:49:18 INFO]: [Insights] Loaded limit 'bed-limit.yml'
[00:49:18 INFO]: [Insights] Loaded limit 'redstone-limit.yml'
[00:49:18 INFO]: [Insights] Loaded limit 'tile-limit.yml'
[00:49:19 ERROR]: Error occurred while enabling Insights v6.13.0 (Is it up to date?)
dev.frankheijden.insights.dependencies.cloud.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: paper brigadier initialization failure (null)
        at dev.frankheijden.insights.dependencies.cloud.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:134) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.Insights.loadCommands(Insights.java:305) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.Insights.onEnable(Insights.java:155) ~[Insights-6.13.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:630) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:544) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:338) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at dev.frankheijden.insights.dependencies.cloud.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:109) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.dependencies.cloud.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:103) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.dependencies.cloud.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:78) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.dependencies.cloud.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:82) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.dependencies.cloud.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:75) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.dependencies.cloud.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:72) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.dependencies.cloud.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:128) ~[Insights-6.13.0.jar:?]
        ... 13 more
Caused by: java.lang.IllegalStateException: Could not find Registry Registry field
        at dev.frankheijden.insights.dependencies.cloud.bukkit.internal.RegistryReflection.lambda$static$2(RegistryReflection.java:71) ~[Insights-6.13.0.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at dev.frankheijden.insights.dependencies.cloud.bukkit.internal.RegistryReflection.<clinit>(RegistryReflection.java:71) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.dependencies.cloud.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:109) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.dependencies.cloud.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:103) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.dependencies.cloud.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:78) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.dependencies.cloud.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:82) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.dependencies.cloud.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:75) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.dependencies.cloud.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:72) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.dependencies.cloud.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:128) ~[Insights-6.13.0.jar:?]
        ... 13 more
[00:49:19 INFO]: [Insights] Disabling Insights v6.13.0`

**Comment by mayberks** [comment]
Yes, I see the problem, you haven't updated the plugin in the spigotmc channel. Now I downloaded it from Github and it is activated. Thank you!
