### ISSUE TITLE
New 1.19.4 support not working

### ISSUE THREAD

**Issue by Izanaagii** [InsightsPlugin/Insights#195]
Hi, on the new .jar for 1.19.4 support I get this.
In addition, my Insights plugin is not working on /pl command,
![Capture d'écran 2023-04-21 092009](https://user-images.githubusercontent.com/86490479/233677109-a5abea13-88cc-4c9b-9b9a-be06cfef4832.png)

**Comment by StKillReal** [comment]
Yep, I confirm this issue

**Comment by frogglen** [comment]
I am also having problems with Insights in 1.19.4, I am using the latest version and for some reason even though I put the worlds I want it to scan it seems to scan them all and sometimes I get errors in the console that there has been an error when scanning the chunk on the map and it does not let me put chests, shulkers and other items.

**Comment by Izanaagii** [comment]
When will it be fixed ?

**Comment by StKillReal** [comment]
> When will it be fixed ?

Seems like develpoer is not interested in this plugin anymore, ot don't have enough time

**Comment by Izanaagii** [comment]
Please fix your plugin.

**Comment by FrankHeijden** [comment]
Can you share your `messages.yml`? It seems it crashes because the key `messages.prefix` does not exist. Could you try with a clean messages.yml?

I am unable to reproduce this issue with a fresh install of Insights 6.14.1 & Paper 530.

I have also bumped the dependencies of adventure / minimessage, could you try with the latest [github actions build](https://github.com/InsightsPlugin/Insights/actions/runs/4967767928)?

**Comment by Izanaagii** [comment]
Once I load the plugin it spamming my console 
![image](https://github.com/InsightsPlugin/Insights/assets/86490479/483d7be1-1a43-4c41-ae8d-d8a8188ef5d5)

**Comment by Izanaagii** [comment]
I tried with the last version you upload on https://github.com/InsightsPlugin/Insights/actions/runs/4967767928

**Comment by FrankHeijden** [comment]
Please show the output of the `version` command

**Comment by StKillReal** [comment]
> I tried with the last version you upload on https://github.com/InsightsPlugin/Insights/actions/runs/4967767928

Take the last version in discord

**Comment by frogglen** [comment]
> Once I load the plugin it spamming my console ![image](https://user-images.githubusercontent.com/86490479/238183639-483d7be1-1a43-4c41-ae8d-d8a8188ef5d5.png)

this is happening to me on 1.19.4

**Comment by frogglen** [comment]
I am using the latest version here where you updated the dependencies.

**Comment by anjoismysign** [comment]
Are you trolls? This guy is giving you a tremendous resource for free! From his spare time!
You were already told to provide the output of "/version" command.
Why can't you type a single command?????????????????

**Comment by frogglen** [comment]
> At least for @Izanaagii , the issue seems to be occurring with an older version of Purpur; the version they were on was 1952. I tried Insights on that version and it indeed gave me similar errors. When bumping the server jar to 1972, it doesn't happen.
> 
> @frogglen are you on Purpur? If so, can you try bumping the version?

i am using purpur most recent version
this happened to me yesterday and it was completely up to date
Current: git-Purpur-1976 (MC: 1.19.4)*

**Comment by frogglen** [comment]
> At least for @Izanaagii , the issue seems to be occurring with an older version of Purpur; the version they were on was 1952. I tried Insights on that version and it indeed gave me similar errors. When bumping the server jar to 1972, it doesn't happen.
> 
> @frogglen are you on Purpur? If so, can you try bumping the version?

this does not happen at the beginning, it happens after the server has been on for a while.
i am using https://github.com/InsightsPlugin/Insights/actions/runs/4967767928

**Comment by frogglen** [comment]
[2023-05-16-3.log.gz](https://github.com/InsightsPlugin/Insights/files/11499529/2023-05-16-3.log.gz)
my full logs

**Comment by MrButtersDEV** [comment]
> > Once I load the plugin it spamming my console ![image](https://user-images.githubusercontent.com/86490479/238183639-483d7be1-1a43-4c41-ae8d-d8a8188ef5d5.png)
> 
> this is happening to me on 1.19.4

This occurs on 1.20 as well (using latest version of the plugin)

**Comment by frogglen** [comment]
any solution?

**Comment by frogglen** [comment]
still happen in 1.20.1
pufferfish

**Comment by frogglen** [comment]
```
[03:27:41 ERROR]: [Insights] java.util.concurrent.TimeoutException
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194) ~[?:?]
        at java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2920) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.util.concurrent.TimeoutException
        ... 7 more
```

**Comment by FrankHeijden** [comment]
Please test on latest version, and notify me of the plugin version you're using + exact server jar (output from /version)
