### ISSUE TITLE
Wont load or work with  mohist

### ISSUE THREAD

**Issue by funnycubeguy** [InsightsPlugin/Insights#212]
I am running Mohist 1.20.1 (spigot+paper+forge) 
https://new.mohistmc.com/downloadSoftware?project=mohist&projectVersion=1.20.1

I tried the different versions from modrinth that support 1.20.1

I get this on load:
```[11:29:00] [Server thread/INFO] [dev.frankheijden.insights.Insights]: [Insights] Enabling Insights v6.17.0
[11:29:00] [Server thread/ERROR] [Minecraft]: Error occurred while enabling Insights v6.17.0 (Is it up to date?)
java.lang.RuntimeException: Insights is incompatible with your server version
	at dev.frankheijden.insights.Insights.onEnable(Insights.java:134) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.17-universal.jar%23983!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.17-universal.jar%23983!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.17-universal.jar%23983!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549) ~[forge-1.20.1-47.2.17-universal.jar%23983!/:997de31d-ddc9a2dad-d2eba2c8-47.2.17]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462) ~[forge-1.20.1-47.2.17-universal.jar%23983!/:997de31d-ddc9a2dad-d2eba2c8-47.2.17]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23978!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23978!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:219) ~[server-1.20.1-20230612.114412-srg.jar%23978!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:850) ~[server-1.20.1-20230612.114412-srg.jar%23978!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23978!/:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
[11:29:00] [Server thread/INFO] [dev.frankheijden.insights.Insights]: [Insights] Disabling Insights v6.17.0
[11:29:00] [Server thread/ERROR] [Minecraft]: Error occurred while disabling Insights v6.17.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.frankheijden.insights.listeners.manager.ListenerManager.unregister()" because "this.listenerManager" is null
	at dev.frankheijden.insights.Insights.onDisable(Insights.java:185) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:349) ~[forge-1.20.1-47.2.17-universal.jar%23983!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:365) ~[forge-1.20.1-47.2.17-universal.jar%23983!/:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:507) ~[forge-1.20.1-47.2.17-universal.jar%23983!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) ~[forge-1.20.1-47.2.17-universal.jar%23983!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.17-universal.jar%23983!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549) ~[forge-1.20.1-47.2.17-universal.jar%23983!/:997de31d-ddc9a2dad-d2eba2c8-47.2.17]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462) ~[forge-1.20.1-47.2.17-universal.jar%23983!/:997de31d-ddc9a2dad-d2eba2c8-47.2.17]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23978!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23978!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:219) ~[server-1.20.1-20230612.114412-srg.jar%23978!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:850) ~[server-1.20.1-20230612.114412-srg.jar%23978!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23978!/:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]```

**Comment by FrankHeijden** [comment]
We don't support mohist
