### ISSUE TITLE
Please add 1.20.6 support.

### ISSUE THREAD

**Issue by Leahcimkrob** [InsightsPlugin/Insights#215]
Massage in log:

[12:44:59] [Server thread/INFO]: [Insights] Enabling Insights v6.17.2
[12:44:59] [Server thread/ERROR]: Error occurred while enabling Insights v6.17.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at Insights-6.17.2.jar/dev.frankheijden.insights.Insights.onEnable(Insights.java:109) ~[Insights-6.17.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-79-f175193]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-79-f175193]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-79-f175193]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-79-f175193]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[paper-1.20.6.jar:1.20.6-79-f175193]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-79-f175193]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-79-f175193]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1139) ~[paper-1.20.6.jar:1.20.6-79-f175193]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-79-f175193]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "raftbukkit"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Integer.java:662) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Integer.java:778) ~[?:?]
	at Insights-6.17.2.jar/dev.frankheijden.insights.dependencies.minecraftreflection.MinecraftReflectionVersion.<clinit>(MinecraftReflectionVersion.java:17) ~[Insights-6.17.2.jar:?]
	... 13 more
[12:44:59] [Server thread/INFO]: [Insights] Disabling Insights v6.17.2

**Comment by StKillReal** [comment]
it's time to wait for few monthes ;)

**Comment by FrankHeijden** [comment]
https://modrinth.com/plugin/insights/version/6.18.0
