### ISSUE TITLE
NoSuchMethodError spamming console

### ISSUE THREAD

**Issue by SlimeDog** [InsightsPlugin/Insights#57]
Spigot 1.16.5-3007
Insights 6.0.0-RC1 with default configuration

On server start-up, every tick yields
```
[09:28:07] [Server thread/WARN]: [Insights] Task #46 for Insights v6.0.0-RC1 generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.Entity.isTicking()Z
        at dev.frankheijden.insights.tasks.EntityTrackerTask.run(EntityTrackerTask.java:37) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by FrankHeijden** [comment]
Interesting! Seems like spigot doesnt implement that one! Fixed!

**Comment by SlimeDog** [comment]
Testing on Spigot (as well as Paper) is advised. The plugin is released on the Spigot forum.

**Comment by FrankHeijden** [comment]
Insights is tested on Spigot, this runnable is specifically made to support spigot servers as they are missing some functionality. I saw an error in the runnable which caused it to call way to frequently as it wasnt clearing unloaded; and used isTicking to check whether an entity is in a loaded chunk or not. Apparently this small feature is a difference between spigot and paper, one which I didnt expect. Small issues sometimes slip through ;)

**Comment by SlimeDog** [comment]
Confirmed fixed with RC2. Thanks.
